=== 01Karmen010McGuire10/repository/2007/2007-09.sodc-alistair-miles/sodc/SoDC-0.2/constraints/sodc-cl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id: sodc-cl.xsd,v 1.1 2007/08/30 23:39:09 ajm65 Exp $ -->
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:cl="http://purl.org/net/sodc/cl"
  targetNamespace="http://purl.org/net/sodc/cl"
  attributeFormDefault="unqualified"
  elementFormDefault="qualified">

  <xs:element name="constraints">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="profile" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="constraint" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:choice>
                    <xs:element name="cardinality" type="xs:integer"/>
                    <xs:element name="mincardinality" type="xs:integer"/>
                    <xs:element name="maxcardinality" type="xs:integer"/>
                    <xs:element name="value">
                      <xs:complexType>
                        <xs:choice>
                          <xs:element name="uri"/>
                          <xs:element name="nodeid"/>
                          <xs:element name="plainliteral">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="lang" minOccurs="0" maxOccurs="1">
                                  <xs:complexType>
                                    <xs:attribute name="use" use="optional" default="required">
                                      <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                          <xs:enumeration value="required"/>
                                          <xs:enumeration value="optional"/>
                                        </xs:restriction>
                                      </xs:simpleType>
                                    </xs:attribute>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:choice>
                      </xs:complexType>
                    </xs:element>
                  </xs:choice>
                  <xs:attribute name="property" type="xs:anyURI" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="uri" type="xs:anyURI" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    <xs:key name="uri">
      <xs:selector xpath="cl:profile"/>
      <xs:field xpath="@uri"/>
    </xs:key>
  </xs:element>
  
</xs:schema>
<!-- 
$Log: sodc-cl.xsd,v $
Revision 1.1  2007/08/30 23:39:09  ajm65
Initial version.
  
-->

=== 01Karmen010McGuire10/repository/2007/2007-09.sodc-alistair-miles/sodc/SoDC-0.2/constraints/examples/simple-constraints.xml
<?xml version="1.0" encoding="UTF-8"?>
<constraints name="simple constraints" 
  xmlns="http://purl.org/net/sodc/cl"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://purl.org/net/sodc/cl ../sodc-cl.xsd">

  <profile uri="http://example.com/profile/simple#book">
    <constraint property="http://purl.org/dc/elements/1.1/title">
      <cardinality>1</cardinality>
    </constraint>
    <constraint property="http://purl.org/dc/elements/1.1/title">
      <value>
        <plainliteral/>
      </value>
    </constraint>
    <constraint property="http://purl.org/dc/elements/1.1/creator">
      <mincardinality>1</mincardinality>
    </constraint>
    <constraint property="http://purl.org/dc/elements/1.1/creator">
      <value>
        <uri/>
      </value>
    </constraint>
  </profile>
  
  <profile uri="http://example.com/profile/simple#person">
    <constraint property="http://xmlns.com/foaf/0.1/name">
      <mincardinality>1</mincardinality>
    </constraint>
    <constraint property="http://xmlns.com/foaf/0.1/name">
      <value>
        <plainliteral/>
      </value>
    </constraint>
  </profile>
  
</constraints>

=== 01Karmen010McGuire10/repository/2007/2007-09.sodc-alistair-miles/sodc/SoDC-0.2/constraints/examples/test-constraints.xml
<?xml version="1.0" encoding="UTF-8"?>
<constraints name="test constraints" 
  xmlns="http://purl.org/net/sodc/cl"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://purl.org/net/sodc/cl ../sodc-cl.xsd">

  <profile uri="http://example.com/profile/test#foo">

    <!-- exact cardinality constraint -->
    <constraint property="http://example.com/property#a">
      <cardinality>1</cardinality>
    </constraint>
    
    <!-- maximum cardinality constraint -->
    <constraint property="http://example.com/property#b">
      <maxcardinality>1</maxcardinality>
    </constraint>
    
    <!-- minimum cardinality constraint -->
    <constraint property="http://example.com/property#c">
      <mincardinality>1</mincardinality>
    </constraint>
    
    <!-- URI-only value constraint -->
    <constraint property="http://example.com/property#d">
      <value>
        <uri/>
      </value>
    </constraint>
    
    <!-- Nodeid-only value constraint -->
    <constraint property="http://example.com/property#e">
      <value>
        <nodeid/>
      </value>
    </constraint>
    
    <!-- Plain literal-only value constraint (lang optional, variable) -->
    <constraint property="http://example.com/property#f">
      <value>
        <plainliteral>
          <lang use="optional"/>
        </plainliteral>
      </value>
    </constraint>

    <!-- Plain literal-only value constraint (lang required, variable) -->
    <constraint property="http://example.com/property#g">
      <value>
        <plainliteral>
          <lang use="required"/>
        </plainliteral>
      </value>
    </constraint>

  </profile>
  
</constraints>
