=== 01Karmen010McGuire10/repository/2007/2007-09.sodc-alistair-miles/sodc/SoDC-0.2/xml/sodc-xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id: sodc-xml.xsd,v 1.2 2007/09/03 09:09:37 ajm65 Exp $ -->
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:sodc="http://purl.org/net/sodc/xml"
  targetNamespace="http://purl.org/net/sodc/xml"
  attributeFormDefault="unqualified"
  elementFormDefault="qualified">

  <xs:element name="graph">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="resource" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:choice minOccurs="0" maxOccurs="1">
                <xs:element name="uri" type="xs:anyURI"/>
                <xs:element name="nodeid" type="xs:string"/>
              </xs:choice>
              <xs:element name="profile" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="property" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="value" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:choice>
                          <xs:element name="uri" type="xs:anyURI"/>
                          <xs:element name="nodeid" type="xs:string"/>
                          <xs:element name="plainliteral">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="lang" type="xs:string" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="typedliteral">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="datatype" type="xs:anyURI" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="xmlliteral">
                            <xs:complexType>
                              <xs:complexContent>
                                <xs:extension base="xs:anyType">
                                </xs:extension>
                              </xs:complexContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:choice>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="uri" use="required" type="xs:anyURI"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="property-value-uri">
            <xs:selector xpath="sodc:property"/>
            <xs:field xpath="@uri"/>
            <xs:field xpath="sodc:value/sodc:uri"/>
          </xs:unique>
          <xs:unique name="property-value-nodeid">
            <xs:selector xpath="sodc:property"/>
            <xs:field xpath="@uri"/>
            <xs:field xpath="sodc:value/sodc:nodeid"/>
          </xs:unique>
          <xs:unique name="property-value-plainliteral">
            <xs:selector xpath="sodc:property"/>
            <xs:field xpath="@uri"/>
            <xs:field xpath="sodc:value/sodc:plainliteral"/>
            <xs:field xpath="sodc:value/sodc:plainliteral/@lang"/>
          </xs:unique>
          <xs:unique name="property-value-typedliteral">
            <xs:selector xpath="sodc:property"/>
            <xs:field xpath="@uri"/>
            <xs:field xpath="sodc:value/sodc:typedliteral"/>
            <xs:field xpath="sodc:value/sodc:typedliteral/@datatype"/>
          </xs:unique>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="uri" use="optional" type="xs:anyURI"/>
    </xs:complexType>    
    <xs:unique name="uri">
      <xs:selector xpath="sodc:resource"/>
      <xs:field xpath="sodc:uri"/>
    </xs:unique>
    <xs:unique name="nodeid">
      <xs:selector xpath="sodc:resource"/>
      <xs:field xpath="sodc:nodeid"/>
    </xs:unique>
  </xs:element>  
   
</xs:schema>
<!--  
$Log: sodc-xml.xsd,v $
Revision 1.2  2007/09/03 09:09:37  ajm65
Added property/value uniqueness constraints; made @lang required on plain literal values (needed to support property/value uniqueness constraint).

Revision 1.1  2007/08/30 23:42:05  ajm65
Initial version.
  
-->

=== 01Karmen010McGuire10/repository/2007/2007-09.sodc-alistair-miles/sodc/SoDC-0.2/xml/examples/schema-test1.xml
<?xml version="1.0" encoding="UTF-8"?>
<graph xmlns="http://purl.org/net/sodc/xml"
  xmlns:eg="http://example.com/xmlns"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://purl.org/net/sodc/xml ../sodc-xml.xsd">

  <!-- test disallow repeat property/value pair -->
  
  <!-- this one should be broken -->
  <resource>
    <property uri="http://example.com/property#p">
      <value>
        <uri>http://example.com/foo</uri>
      </value>
    </property>
    <property uri="http://example.com/property#p">
      <value>
        <uri>http://example.com/foo</uri>
      </value>
    </property>
  </resource>
  
  <!-- this one should be ok -->
  <resource>
    <property uri="http://example.com/property#p">
      <value>
        <uri>http://example.com/foo</uri>
      </value>
    </property>
    <property uri="http://example.com/property#p">
      <value>
        <uri>http://example.com/bar</uri>
      </value>
    </property>
  </resource>
  
  <!-- this one should be broken -->
  <resource>
    <property uri="http://example.com/property#p">
      <value>
        <nodeid>foo</nodeid>
      </value>
    </property>
    <property uri="http://example.com/property#p">
      <value>
        <nodeid>foo</nodeid>
      </value>
    </property>
  </resource>
  
  <!-- this one should be ok -->
  <resource>
    <property uri="http://example.com/property#p">
      <value>
        <nodeid>foo</nodeid>
      </value>
    </property>
    <property uri="http://example.com/property#p">
      <value>
        <nodeid>bar</nodeid>
      </value>
    </property>
  </resource>
  
  <!-- this one should be broken -->
  <resource>
    <property uri="http://example.com/property#p">
      <value>
        <plainliteral lang="">foo</plainliteral>
      </value>
    </property>
    <property uri="http://example.com/property#p">
      <value>
        <plainliteral lang="">foo</plainliteral>
      </value>
    </property>
  </resource>
  
  <!-- this one should be broken -->
  <resource>
    <property uri="http://example.com/property#p">
      <value>
        <plainliteral lang="en">foo</plainliteral>
      </value>
    </property>
    <property uri="http://example.com/property#p">
      <value>
        <plainliteral lang="en">foo</plainliteral>
      </value>
    </property>
  </resource>
  
  <!-- this one should be ok -->
  <resource>
    <property uri="http://example.com/property#p">
      <value>
        <plainliteral lang="">foo</plainliteral>
      </value>
    </property>
    <property uri="http://example.com/property#p">
      <value>
        <plainliteral lang="">bar</plainliteral>
      </value>
    </property>
  </resource>
  
  <!-- this one should be ok -->
  <resource>
    <property uri="http://example.com/property#p">
      <value>
        <plainliteral lang="en">foo</plainliteral>
      </value>
    </property>
    <property uri="http://example.com/property#p">
      <value>
        <plainliteral lang="fr">foo</plainliteral>
      </value>
    </property>
  </resource>

  <!-- this one should be broken -->
  <resource>
    <property uri="http://example.com/property#p">
      <value>
        <typedliteral datatype="http://example.com/datatype#foo">foo</typedliteral>
      </value>
    </property>
    <property uri="http://example.com/property#p">
      <value>
        <typedliteral datatype="http://example.com/datatype#foo">foo</typedliteral>
      </value>
    </property>
  </resource>
  
  <!-- this one should be ok -->
  <resource>
    <property uri="http://example.com/property#p">
      <value>
        <typedliteral datatype="http://example.com/datatype#foo">foo</typedliteral>
      </value>
    </property>
    <property uri="http://example.com/property#p">
      <value>
        <typedliteral datatype="http://example.com/datatype#foo">bar</typedliteral>
      </value>
    </property>
  </resource>
  
  <!-- this one should be ok -->
  <resource>
    <property uri="http://example.com/property#p">
      <value>
        <typedliteral datatype="http://example.com/datatype#foo">foo</typedliteral>
      </value>
    </property>
    <property uri="http://example.com/property#p">
      <value>
        <typedliteral datatype="http://example.com/datatype#bar">foo</typedliteral>
      </value>
    </property>
  </resource>
  
  <!-- N.B. cannot disallow repeat xml literal values using uniqueness constraint, because requires simple type in unique field(s) -->
  
  <!-- this should be broken -->
  <resource>
    <property uri="http://example.com/property#p">
      <value>
        <xmlliteral>
          <eg:foo>bar</eg:foo>
        </xmlliteral>
      </value>
    </property>
    <property uri="http://example.com/property#p">
      <value>
        <xmlliteral>
          <eg:foo>bar</eg:foo>
        </xmlliteral>
      </value>
    </property>
  </resource>
  
</graph>

=== 01Karmen010McGuire10/repository/2007/2007-09.sodc-alistair-miles/sodc/SoDC-0.2/constraints/examples/simple-graph.xml
<?xml version="1.0" encoding="UTF-8"?>
<?oxygen SCHSchema="simple.sch"?>
<graph 
  xmlns="http://purl.org/net/sodc/xml"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://purl.org/net/sodc/xml ../../xml/sodc-xml.xsd">  

  <resource>
    <uri>http://example.com/book#1</uri>
    <profile>http://example.com/profile/simple#book</profile>
    <property uri="http://purl.org/dc/elements/1.1/title">
      <value>
        <plainliteral lang="en">Winnie the Pooh</plainliteral>
      </value>
    </property>
    <property uri="http://purl.org/dc/elements/1.1/creator">
      <value>
        <uri>http://example.com/person#1</uri>
      </value>
    </property>
  </resource>

  <resource>
    <uri>http://example.com/person#1</uri>
    <profile>http://example.com/profile/simple#person</profile>
    <property uri="http://xmlns.com/foaf/0.1/name">
      <value>
        <plainliteral lang="en">A. A. Milne</plainliteral>
      </value>
    </property>
  </resource>
  
</graph>

=== 01Karmen010McGuire10/repository/2007/2007-09.sodc-alistair-miles/sodc/SoDC-0.2/xml/examples/schema-test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<graph xmlns="http://purl.org/net/sodc/xml"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://purl.org/net/sodc/xml ../sodc-xml.xsd">

  <!-- test disallow repeat resource descriptions -->  

  <resource>
    <uri>http://example.com/foo</uri>
    <property uri="http://example.com/property#p">
      <value>
        <plainliteral lang="en">foo</plainliteral>
      </value>
    </property>
  </resource>

  <!-- this should be broken -->
  <resource>
    <uri>http://example.com/foo</uri>
    <property uri="http://example.com/property#p">
      <value>
        <plainliteral lang="en">foo</plainliteral>
      </value>
    </property>
  </resource>

  <!-- this should be ok -->
  <resource>
    <uri>http://example.com/bar</uri>
    <property uri="http://example.com/property#p">
      <value>
        <plainliteral lang="en">foo</plainliteral>
      </value>
    </property>
  </resource>
  
  <!-- this should be ok -->
  <resource>
    <nodeid>foo</nodeid>
    <property uri="http://example.com/property#p">
      <value>
        <plainliteral lang="en">foo</plainliteral>
      </value>
    </property>
  </resource>
  
  <!-- this should be broken -->
  <resource>
    <nodeid>foo</nodeid>
    <property uri="http://example.com/property#p">
      <value>
        <plainliteral lang="en">foo</plainliteral>
      </value>
    </property>
  </resource>
  
  <!-- this should be ok -->
  <resource>
    <nodeid>bar</nodeid>
    <property uri="http://example.com/property#p">
      <value>
        <plainliteral lang="en">foo</plainliteral>
      </value>
    </property>
  </resource>
  
</graph>

=== 01Karmen010McGuire10/repository/2007/2007-09.sodc-alistair-miles/sodc/SoDC-0.2/xml/examples/graph6.xml
<?xml version="1.0" encoding="UTF-8"?>
<graph 
  xmlns="http://purl.org/net/sodc/xml"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://purl.org/net/sodc/xml ../sodc-xml.xsd">  

  <resource>
    <property uri="http://purl.org/dc/elements/1.1/title">
      <value>
        <plainliteral lang="en">Winnie the Pooh</plainliteral>
      </value>
    </property>
    <property uri="http://purl.org/dc/elements/1.1/creator">
      <value>
        <nodeid>xyz</nodeid>
      </value>
    </property>
  </resource>

  <resource>
    <nodeid>xyz</nodeid>
    <property uri="http://xmlns.com/foaf/0.1/name">
      <value>
        <plainliteral lang="en">A. A. Milne</plainliteral>
      </value>
    </property>
  </resource>
  
</graph>

=== 01Karmen010McGuire10/repository/2007/2007-09.sodc-alistair-miles/sodc/SoDC-0.2/xml/examples/graph4.xml
<?xml version="1.0" encoding="UTF-8"?>
<graph 
  xmlns="http://purl.org/net/sodc/xml"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://purl.org/net/sodc/xml ../sodc-xml.xsd">  

  <resource>
    <uri>http://example.com/book#1</uri>
    <property uri="http://purl.org/dc/elements/1.1/title">
      <value>
        <plainliteral lang="en">Winnie the Pooh</plainliteral>
      </value>
    </property>
    <property uri="http://purl.org/dc/elements/1.1/creator">
      <value>
        <uri>http://example.com/person#1</uri>
      </value>
    </property>
    <property uri="http://example.com/property#price">
      <value>
        <typedliteral datatype="http://www.w3.org/2001/XMLSchema#decimal">9.99</typedliteral>
      </value>
    </property>
  </resource>

  <resource>
    <uri>http://example.com/person#1</uri>
    <property uri="http://xmlns.com/foaf/0.1/name">
      <value>
        <plainliteral lang="en">A. A. Milne</plainliteral>
      </value>
    </property>
  </resource>
  
</graph>

=== 01Karmen010McGuire10/repository/2007/2007-09.sodc-alistair-miles/sodc/SoDC-0.2/constraints/examples/test-graph.xml
<?xml version="1.0" encoding="UTF-8"?>
<?oxygen SCHSchema="test.sch"?>
<graph 
  xmlns="http://purl.org/net/sodc/xml"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://purl.org/net/sodc/xml ../../xml/sodc-xml.xsd">
    
  <resource>
    <uri>http://example.com/resource#foo</uri>
    <profile>http://example.com/profile/test#foo</profile>
    
    <!-- violate an exact cardinality constraint of 1 (comment to fix) -->

    <property uri="http://example.com/property#a">
      <value>
        <plainliteral>foo</plainliteral>
      </value>
    </property>
    
    <property uri="http://example.com/property#a">
      <value>
        <plainliteral>bar</plainliteral>
      </value>
    </property>
    
    <!-- violate a maximum cardinality constraint of 1 (comment to fix) -->

    <property uri="http://example.com/property#b">
      <value>
        <plainliteral>foo</plainliteral>
      </value>
    </property>
    
    <property uri="http://example.com/property#b">
      <value>
        <plainliteral>bar</plainliteral>
      </value>
    </property>
    
    <!-- violate a minimum cardinality constraint of 1 (uncomment to fix) -->
<!--  
    <property uri="http://example.com/property#c">
      <value>
        <plainliteral>foo</plainliteral>
      </value>
    </property>  
-->

    <!-- violate URI-only value constraint -->
    
    <property uri="http://example.com/property#d">
      <value>
        <plainliteral>foo</plainliteral>
      </value>
    </property>

    <property uri="http://example.com/property#d">
      <value>
        <nodeid>foo</nodeid>
      </value>
    </property>
    
    <property uri="http://example.com/property#d">
      <value>
        <typedliteral datatype="http://example.com/datatype#foo">bar</typedliteral>
      </value>
    </property>
    
    <!-- violate nodeid-only value constraint -->
    
    <property uri="http://example.com/property#e">
      <value>
        <plainliteral>foo</plainliteral>
      </value>
    </property>
    
    <property uri="http://example.com/property#e">
      <value>
        <uri>http://example.com/resource#bar</uri>
      </value>
    </property>
    
    <property uri="http://example.com/property#e">
      <value>
        <typedliteral datatype="http://example.com/datatype#foo">bar</typedliteral>
      </value>
    </property>

    <!-- violate plain literal-only value constraint (lang optional, variable) -->
      
    <property uri="http://example.com/property#f">
      <value>
        <uri>http://example.com/resource#bar</uri>
      </value>
    </property>
    
    <property uri="http://example.com/property#f">
      <value>
        <nodeid>bar</nodeid>
      </value>
    </property>
    
    <property uri="http://example.com/property#f">
      <value>
        <typedliteral datatype="http://example.com/datatype#foo">bar</typedliteral>
      </value>
    </property>
    
    <!-- violate plain literal-only value constraint (lang required, variable) -->
      
    <property uri="http://example.com/property#g">
      <value>
        <uri>http://example.com/resource#bar</uri>
      </value>
    </property>
    
    <property uri="http://example.com/property#g">
      <value>
        <nodeid>bar</nodeid>
      </value>
    </property>
    
    <property uri="http://example.com/property#g">
      <value>
        <typedliteral datatype="http://example.com/datatype#foo">bar</typedliteral>
      </value>
    </property>
      
    <property uri="http://example.com/property#g">
      <value>
        <plainliteral>foo</plainliteral>
      </value>
    </property>      
    
  </resource>
  
</graph>
